[package]
name = "rewards-interfaces"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw4.workspace = true
cosmwasm-std.workspace = true
cosmwasm-schema.workspace = true
kujira.workspace = true
thiserror.workspace = true
serde = { workspace = true, default-features = false, features = ["derive"] }
